# Generated by Django 4.1 on 2022-11-28 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='count_auth',
        ),
    ]
