# Generated by Django 4.1 on 2022-11-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_api', '0002_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('ta', 'TA'), ('fa', 'FA')], default='ta', max_length=255),
        ),
    ]
