# Generated by Django 4.1 on 2022-11-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_api', '0004_alter_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('TwoAnswers', 'Two Answers'), ('FourAnswers', 'Four Answers')], default='ta', max_length=255),
        ),
    ]
