# Generated by Django 4.1 on 2022-11-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_api', '0005_alter_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='trivia',
        ),
        migrations.AddField(
            model_name='trivia',
            name='questions',
            field=models.ManyToManyField(blank=True, to='trivia_api.question'),
        ),
    ]
