# Generated by Django 4.1 on 2022-11-27 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_api', '0007_remove_trivia_questions_question_trivia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialog', models.TextField(blank=True, max_length=510, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('trivia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trivia_api.trivia')),
            ],
        ),
    ]
