# Generated by Django 4.1 on 2022-11-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_api', '0008_dialog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('TrueOrFalse', 'TrueOrFalse'), ('FourAnswers', 'FourAnswers')], default='FourAnswers', max_length=255),
        ),
    ]
