# Generated by Django 4.1 on 2022-11-27 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_api', '0009_alter_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trivia',
            name='title',
        ),
    ]
