# Generated by Django 4.1 on 2022-11-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_api', '0010_remove_trivia_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialog',
            name='trivia',
        ),
        migrations.RemoveField(
            model_name='question',
            name='trivia',
        ),
        migrations.AddField(
            model_name='trivia',
            name='dialogs',
            field=models.ManyToManyField(blank=True, to='trivia_api.dialog'),
        ),
        migrations.AddField(
            model_name='trivia',
            name='questions',
            field=models.ManyToManyField(blank=True, to='trivia_api.question'),
        ),
    ]
