# Generated by Django 4.1 on 2022-11-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_api', '0011_remove_dialog_trivia_remove_question_trivia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('TwoAnswers', 'TwoAnswers'), ('FourAnswers', 'FourAnswers')], default='FourAnswers', max_length=255),
        ),
    ]
