# Generated by Django 4.1 on 2022-11-27 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_api', '0012_alter_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='published',
        ),
    ]
