# Generated by Django 4.1 on 2022-11-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_api', '0014_remove_answer_question_question_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trivia',
            name='dialogs',
        ),
        migrations.AddField(
            model_name='question',
            name='explication',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.DeleteModel(
            name='Dialog',
        ),
    ]
