# Generated by Django 4.1 on 2022-11-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_api', '0015_remove_trivia_dialogs_question_explication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='has_explication',
            field=models.BooleanField(default=False),
        ),
    ]
