# Generated by Django 4.1 on 2022-11-27 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0008_alter_topic_featured'),
        ('trivia_api', '0016_question_has_explication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trivia',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_api.topic'),
        ),
    ]
