# Generated by Django 4.1 on 2022-11-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_api', '0018_alter_question_type_delete_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trivia',
            old_name='published',
            new_name='is_published',
        ),
        migrations.AddField(
            model_name='question',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
