# Generated by Django 4.0 on 2022-12-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_api', '0019_rename_published_trivia_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(blank=True, to='trivia_api.Answer'),
        ),
        migrations.AlterField(
            model_name='trivia',
            name='questions',
            field=models.ManyToManyField(blank=True, to='trivia_api.Question'),
        ),
    ]
