# Generated by Django 4.0 on 2023-02-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_api', '0022_alter_trivia_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='trivia',
            name='trivia_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trivia',
            name='trivia_paragraph',
            field=models.TextField(blank=True, null=True),
        ),
    ]
