# Generated by Django 4.1 on 2022-11-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='description',
        ),
        migrations.AddField(
            model_name='slot',
            name='name',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
