# Generated by Django 4.1 on 2022-11-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0003_remove_piece_description_piece_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
