# Generated by Django 4.1 on 2022-11-22 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0004_game_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='topic',
        ),
        migrations.AddField(
            model_name='game',
            name='summary',
            field=models.TextField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='topic',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game_api.game'),
        ),
    ]
