# Generated by Django 4.1 on 2022-11-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0005_remove_game_topic_game_summary_topic_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='summary',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='topic',
            name='summary',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
