# Generated by Django 4.1 on 2022-11-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0006_alter_game_summary_alter_topic_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='pieces',
            field=models.ManyToManyField(blank=True, to='game_api.piece'),
        ),
    ]
