# Generated by Django 4.1 on 2022-11-28 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0008_alter_topic_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='published',
            new_name='is_published',
        ),
    ]
