# Generated by Django 4.1 on 2022-11-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0009_rename_published_topic_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='subhead',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
