# Generated by Django 4.1 on 2022-11-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0010_game_subhead'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
