# Generated by Django 4.1 on 2022-11-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0012_game_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='thumbnail_color',
        ),
        migrations.AlterField(
            model_name='game',
            name='color',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('violet', 'VIOLET')], default='black', max_length=6),
        ),
    ]
