# Generated by Django 4.1 on 2022-12-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0013_remove_topic_thumbnail_color_alter_game_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='summary',
            field=models.CharField(blank=True, max_length=145),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=125),
        ),
    ]
