# Generated by Django 4.1 on 2022-12-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0014_alter_topic_summary_alter_topic_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='summary',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=75),
        ),
    ]
