# Generated by Django 4.0 on 2022-12-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0016_alter_game_color_alter_game_pieces'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='level',
            field=models.CharField(choices=[('easy', 'EASY'), ('intermediate', 'INTERMEDIATE'), ('hard', 'HARD')], default='easy', max_length=12),
        ),
    ]
