# Generated by Django 4.0 on 2022-12-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0017_topic_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='level',
            field=models.CharField(choices=[('easy', 'EASY'), ('medium', 'MEDIUM'), ('hard', 'HARD')], default='easy', max_length=12),
        ),
    ]
