# Generated by Django 4.0 on 2022-12-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_api', '0018_alter_topic_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='color',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE')], default='green', max_length=6),
        ),
    ]
